version: '3.8'

services:
  # MongoDB - Catalog Store
  mongodb:
    image: mongo:6.0
    container_name: rocket_mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rocketpassword
    volumes:
      - mongo_data:/data/db
    networks:
      - rocket_network

volumes:
  mongo_data:


networks:
  rocket_network:
    driver: bridge
