import { Injectable, Logger } from '@nestjs/common';
import { RabbitSubscribe, AmqpConnection } from '@golevelup/nestjs-rabbitmq';
import { MarketplaceSyncPayload } from '../dto/marketplace-sync.dto';
import { MarketplaceSyncResult } from '../dto/marketplace-sync-result.dto';
import axios from 'axios';
// import { MarketplaceAuthService } from '../../marketplace/auth/services/marketplace-auth.service';
import { MarketplaceResilienceService } from '../services/marketplace-resilience.service';

@Injectable()
export class MercadoLivreSyncWorker {
    private readonly logger = new Logger(MercadoLivreSyncWorker.name);
    private readonly baseUrl = 'https://api.mercadolibre.com';

    constructor(
        private readonly amqpConnection: AmqpConnection,
        private readonly resilienceService: MarketplaceResilienceService,
    ) { }

    @RabbitSubscribe({
        exchange: 'rocket.marketplace.sync',
        routingKey: 'sync.mercadolivre',
        queue: 'q.sync.mercadolivre',
    })
    async handleSync(msg: MarketplaceSyncPayload) {
        this.logger.log(`[MercadoLivre] Processing job ${msg.jobId} (Attempt ${msg.attemptId}) for listing ${msg.listingId}`);

        const result: MarketplaceSyncResult = {
            jobId: msg.jobId,
            attemptId: msg.attemptId,
            listingId: msg.listingId,
            marketplaceId: msg.marketplaceId,
            success: false,
            action: msg.action,
            timestamp: new Date()
        };

        try {
            await this.resilienceService.execute(msg.marketplaceId, async (token) => {
                const accessToken = token.accessToken;
                if (!accessToken) throw new Error('Access token missing in refreshed token.');

                // Build Headers
                const headers = {
                    Authorization: `Bearer ${accessToken}`,
                    'Content-Type': 'application/json'
                };

                let externalId = null;

                if (msg.action === 'CREATE') {
                    const body = {
                        family_name: msg.payload.title,
                        category_id: this.extractCategoryId(msg.payload.attributes),
                        price: msg.payload.price,
                        currency_id: 'BRL',
                        available_quantity: msg.payload.stock,
                        buying_mode: 'buy_it_now',
                        condition: 'new',
                        listing_type_id: 'gold_pro',
                        seller_custom_field: msg.payload.sku,
                        description: { plain_text: msg.payload.description },
                        pictures: msg.payload.images.map(url => ({ source: url })),
                        attributes: this.mapAttributes(msg.payload.attributes)
                    };
                    this.logger.debug(`[MercadoLivre] CREATE payload for ${externalId}: ${JSON.stringify(body)}`);

                    const response = await axios.post(`${this.baseUrl}/items`, body, { headers });
                    externalId = response.data.id;
                    this.logger.log(`[MercadoLivre] Created item ${externalId}`);

                    // Secondary Call for Description
                    await this.updateDescription(externalId, msg.payload.description, headers);

                } else if (msg.action === 'UPDATE') {
                    if (!msg.externalId) throw new Error("UPDATE action requires externalId in DTO");

                    externalId = msg.externalId;

                    // Build UPDATE payload with only safe fields for User Products API
                    // Note: title/family_name are omitted as they may be auto-generated by ML
                    const body = {
                        price: msg.payload.price,
                        available_quantity: msg.payload.stock,
                        pictures: msg.payload.images.map(url => ({ source: url })),
                        attributes: this.mapAttributes(msg.payload.attributes)
                    };

                    this.logger.debug(`[MercadoLivre] UPDATE payload for ${externalId}: ${JSON.stringify(body)}`);

                    await axios.put(`${this.baseUrl}/items/${externalId}`, body, { headers });
                    this.logger.log(`[MercadoLivre] Updated item ${externalId}`);

                    // Secondary Call for Description
                    await this.updateDescription(externalId, msg.payload.description, headers);
                }

                // Pass externalId out if needed, or set it directly in result (captured in closure)
                result.externalId = externalId;
            });

            result.success = true;


        } catch (error) {
            const statusCode = error.response?.status || 'N/A';
            const errorData = error.response?.data ? JSON.stringify(error.response.data) : error.message;
            const errorMsg = `[Status ${statusCode}] ${errorData}`;

            this.logger.error(`[MercadoLivre] Failed job ${msg.jobId} for action ${msg.action}: ${errorMsg}`);
            this.logger.debug(`[MercadoLivre] Failed payload: ${JSON.stringify(msg.payload)}`);

            result.success = false;
            result.errorMessage = errorMsg;
        } finally {
            // Publish Result
            await this.amqpConnection.publish(
                'rocket.marketplace.results',
                'result.mercadolivre',
                result
            );
        }
    }

    private extractCategoryId(attrs: any[]): string {
        const cat = attrs.find(a => a.id === 'category_id');
        return cat ? cat.value : 'MLB3530';
    }

    private mapAttributes(attrs: any[]) {
        if (!Array.isArray(attrs)) {
            this.logger.warn('Attributes is not an array, falling back to empty list');
            return [];
        }

        return attrs
            .filter(a => a.id !== 'category_id')
            .map(attr => {
                const out: any = { id: attr.id };

                // Logic to handle valueType (copied from Adapter logic)
                if (attr.valueType === 'list') {
                    // For 'list' types, the DB value is the ID
                    out.value_id = attr.value;
                } else if (attr.valueType === 'boolean') {
                    // ML usually wants value_name for boolean if it's not a checkbox ID? 
                    // Adapter said: "Boolean: Send Name/Value"
                    out.value_name = String(attr.value);
                } else {
                    // Check if value looks like a number and might be a legacy ID? 
                    // The Adapter had: if (isNumeric) attributeData.value_id
                    // But let's stick to safe string value_name unless explicitly 'list'
                    out.value_name = String(attr.value);
                }

                return out;
            });
    }

    private async updateDescription(externalId: string, description: string, headers: any) {
        if (!description) return;
        try {
            await axios.put(`${this.baseUrl}/items/${externalId}/description`, {
                plain_text: description
            }, { headers });
            this.logger.log(`[MercadoLivre] Updated description for ${externalId}`);
        } catch (error) {
            this.logger.warn(`[MercadoLivre] Failed to update description for ${externalId}: ${error.message}`);
        }
    }
}
