import { WebhookDispatcher } from './webhook-dispatcher.service';
import { WEBHOOK_DOMAIN_COMMANDS } from '../events/webhook.events';
describe('WebhookDispatcher.dispatch', () => {
  const makeSut = () => { const emitter = { emitAsync: jest.fn().mockResolvedValue([]) }; return { sut: new WebhookDispatcher(emitter as any), emitter }; };
  const base = { marketplace:'mercadolivre', topic:'orders_v2', externalId:'1', resource:'/orders/1', payload:{}, receivedAt:new Date() };
  it('order → ORDER_SYNC_REQUESTED', async () => { const { sut, emitter } = makeSut(); await sut.dispatch({...base, kind:'order'}); expect(emitter.emitAsync).toHaveBeenCalledWith(WEBHOOK_DOMAIN_COMMANDS.ORDER_SYNC_REQUESTED, expect.objectContaining({ marketplace:'mercadolivre', externalOrderId:'1', resource:'/orders/1', source:'webhook' })); });
  it('order_pack → ORDER_PACK_SYNC_REQUESTED', async () => { const { sut, emitter } = makeSut(); await sut.dispatch({...base, kind:'order_pack', externalId:'55', resource:'/packs/55'}); expect(emitter.emitAsync).toHaveBeenCalledWith(WEBHOOK_DOMAIN_COMMANDS.ORDER_PACK_SYNC_REQUESTED, expect.objectContaining({ marketplace:'mercadolivre', externalPackId:'55', source:'webhook' })); });
  it('shipment → SHIPMENT_SYNC_REQUESTED', async () => { const { sut, emitter } = makeSut(); await sut.dispatch({...base, topic:'shipments', kind:'shipment', externalId:'47856425023', resource:'/shipments/47856425023', externalUserId:'9'}); expect(emitter.emitAsync).toHaveBeenCalledWith(WEBHOOK_DOMAIN_COMMANDS.SHIPMENT_SYNC_REQUESTED, expect.objectContaining({ marketplace:'mercadolivre', externalShipmentId:'47856425023', externalUserId:'9', source:'webhook' })); });
  it('question → QUESTION_INGEST_REQUESTED', async () => { const { sut, emitter } = makeSut(); await sut.dispatch({...base, kind:'question', externalId:'77', resource:'/questions/77'}); expect(emitter.emitAsync).toHaveBeenCalledWith(WEBHOOK_DOMAIN_COMMANDS.QUESTION_INGEST_REQUESTED, expect.objectContaining({ externalQuestionId:'77' })); });
  it('moderation → MODERATION_PROBE_REQUESTED', async () => { const { sut, emitter } = makeSut(); await sut.dispatch({...base, topic:'items', kind:'moderation', externalId:'MLB1', resource:'/items/MLB1', externalUserId:'9'}); expect(emitter.emitAsync).toHaveBeenCalledWith(WEBHOOK_DOMAIN_COMMANDS.MODERATION_PROBE_REQUESTED, expect.objectContaining({ marketplace:'mercadolivre', externalId:'MLB1', externalUserId:'9', source:'webhook' })); });
  it('return → RETURN_INGEST_REQUESTED', async () => { const { sut, emitter } = makeSut(); await sut.dispatch({...base, topic:'claims', kind:'return', externalId:'CLM1', resource:'/post-purchase/v1/claims/CLM1', externalUserId:'9'}); expect(emitter.emitAsync).toHaveBeenCalledWith(WEBHOOK_DOMAIN_COMMANDS.RETURN_INGEST_REQUESTED, expect.objectContaining({ marketplace:'mercadolivre', externalId:'CLM1', externalUserId:'9', source:'webhook' })); });
  it('unparseable → não emite', async () => { const { sut, emitter } = makeSut(); await sut.dispatch({...base, kind:'unparseable' as any}); expect(emitter.emitAsync).not.toHaveBeenCalled(); });
  it('order sem externalId → não emite', async () => { const { sut, emitter } = makeSut(); await sut.dispatch({...base, kind:'order', externalId: undefined}); expect(emitter.emitAsync).not.toHaveBeenCalled(); });
});
