import { Injectable, Logger } from '@nestjs/common';
import { RabbitSubscribe } from '@golevelup/nestjs-rabbitmq';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { EventEmitter2 } from '@nestjs/event-emitter';
import { CategoryResolutionService } from '../services/category-resolution.service';

@Injectable()
export class DiscoveryMsResponseConsumer {
    private readonly logger = new Logger(DiscoveryMsResponseConsumer.name);

    constructor(
        @InjectModel('ProductDiscoveryModel')
        private readonly discoveryModel: Model<any>,
        private readonly eventEmitter: EventEmitter2,
        private readonly categoryResolution: CategoryResolutionService,
    ) {
        this.logger.log('DiscoveryMsResponseConsumer initialized');
    }

    @RabbitSubscribe({
        exchange: 'rocket.inventory',
        routingKey: 'discovery.scraper.response',
        queue: 'discovery.scraper.response',
        queueOptions: { durable: true },
    })
    async handleResponse(msg: any) {
        const { jobId, status, results, error, scrapedAt } = msg;
        this.logger.log(`Received discovery response: jobId=${jobId} status=${status}`);

        const updateData: any = {
            updatedAt: new Date(scrapedAt || Date.now()),
        };

        if (status === 'completed') {
            updateData.status = 'done';
            updateData.data = results;

            // Resolve category from categoryPath generated by Gemini
            try {
                const categoryId = await this.categoryResolution.resolve(
                    results?.categoryPath ?? null,
                );
                if (categoryId) {
                    updateData.resolvedCategoryId = categoryId;
                    this.logger.log(`Category resolved for job ${jobId}: ${categoryId}`);
                }
            } catch (err: unknown) {
                const message = err instanceof Error ? err.message : String(err);
                this.logger.warn(`Category resolution failed for job ${jobId}: ${message}`);
            }

            this.logger.log(`Discovery job ${jobId} updated as DONE`);
        } else {
            updateData.status = 'failed';
            updateData.error = error;
            this.logger.error(`Discovery job ${jobId} failed: ${error}`);
        }

        await this.discoveryModel.updateOne(
            { batchId: jobId },
            { $set: updateData }
        ).exec();

        this.eventEmitter.emit('queue.job.update', {
            jobId,
            status: status === 'completed' ? 'COMPLETED' : 'FAILED',
            result: updateData.data,
            error: updateData.error,
        });
    }

    @RabbitSubscribe({
        exchange: 'rocket.inventory',
        routingKey: 'discovery.scraper.progress',
        queue: 'discovery.scraper.progress',
        queueOptions: { durable: true },
    })
    async handleProgress(msg: any) {
        const { jobId, step, message } = msg;
        this.logger.debug(`Discovery progress: jobId=${jobId} step=${step} msg=${message}`);

        this.eventEmitter.emit('queue.job.update', {
            jobId,
            status: 'processing',
            step,
            message,
        });
    }
}
